const apps = [
    {
        logo:"/assets/user.jpg",
        title:"Account",
    },
    {
        logo:"/assets/sheets.png",
        title:"Sheets",
    },
    {
        logo:"/assets/maps.webp",
        title:"maps",
    },
    {
        logo:"/assets/google-icon-title.png",
        title:"Search",
    },
    {
        logo:"/assets/youtube.png",
        title:"youtube",
    },
    {
        logo:"/assets/play.png",
        title:"play",
    },
    {
        logo:"/assets/calender.png",
        title:"calender",
    },
    {
        logo:"/assets/gmail.png",
        title:"gmail",
    },
    {
        logo:"/assets/contacts.png",
        title:"contacts",
    },
    {
        logo:"/assets/gdrive.png",
        title:"drive",
    },
    {
        logo:"/assets/translate.png",
        title:"translate",
    },
    {
        logo:"/assets/photos.png",
        title:"photos",
    },
    {
        logo:"/assets/shopping.png",
        title:"shopping",
    },
    {
        logo:"/assets/business.png",
        title:"business profile",
    },
    {
        logo:"/assets/meet.png",
        title:"Sheets",
    },
    
]